name = "club-hub-web"
compatibility_date = "2024-09-02"
main="./functions/worker.ts"

[[routes]]
zone_id = "club-hub.org"
pattern = "club-hub.org"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[env.dev.vars]
USE_EMULATOR = "true"
GCP_PROJECT_ID = "note-pedia"



